Global:
  use_gpu: True
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
  save_model_dir: /yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug
  # save_model_dir: /yuanhuan/model/image/lpr/paddle_ocr/test
  save_epoch_step: 50
  # evaluation is run every 20000000 iterations after the 4000th iteration
  eval_batch_step: [0, 20000000]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img:
  # for data or label process
  # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
  character_dict_path: /yuanhuan/model/image/lpr/paddle_dict/plate_chile_202312/chile_dict.txt
  max_text_length: 10
  infer_mode: False
  # use_space_char: True
  use_space_char: False  # 训练统一不增加空格标签
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
  in_channels: 1

  Backbone:
    name: MobileNetV1RM
  Neck:
    # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
    name: TCRES
    encoder_type: tcres_mobile_no_reshape
    hidden_size: 128

  Head:
    # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
    name: RMCTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ""
    # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
    label_file_list: ["/yuanhuan/model/image/lpr/paddle_dict/plate_chile_202312/ImageSets/Main/trainval.txt"]

    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
          tia_prob: -1
          crop_prob: -1
          motion_blur_prob: 0.2
          blur_prob: 0.2
          expand_prob: 0.4
          hsv_aug_prob: 0.2
          jitter_prob: -1
          noise_prob: 0.2
          reverse_prob: 0.2
      - CTCLabelEncode: # Class handling label

      # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
      - RMRecResizeImg:
          image_shape: [1, 128, 256]
          padding: False

      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ""
    # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
    label_file_list: ["/yuanhuan/model/image/lpr/paddle_dict/plate_chile_202312/ImageSets/Main/test.txt"]

    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label

      # 18、cnn + tc_res + mobile + RMRESIZE + gray + 128 256 + all data
      - RMRecResizeImg:
          image_shape: [1, 128, 256]
          padding: False

      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 8

# 环境配置
# conda activate py37_paddleocr
# cd /yuanhuan/code/demo/Image/recognition2d/PaddleOCR/

# 模型训练
# python3 tools/train.py -c configs/rec/rmai_ocr/chile/chile_rm_cnn_tc_res.yml -o Global.pretrained_model=
# python3 -m paddle.distributed.launch --gpus '0,1'  tools/train.py -c configs/rec/rmai_ocr/chile/chile_rm_cnn_tc_res.yml -o Global.pretrained_model=/yuanhuan/model/image/lpr/paddle_ocr/v1_us_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202310_w_diffste_w_aug/latest

# 模型验证
# python3 -m paddle.distributed.launch --gpus '0' tools/eval.py -c configs/rec/rmai_ocr/chile/chile_rm_cnn_tc_res.yml -o Global.checkpoints=/yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/best_accuracy
# python3 tools/infer_rec.py -c configs/rec/rmai_ocr/chile/chile_rm_cnn_tc_res.yml -o Global.pretrained_model=/yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/best_accuracy  Global.infer_img=/yuanhuan/data/image/RM_ANPR/training/plate_cn_diffste_202307/diffste_248_111600/Images/0241-7955293-0_chuanV11082-00_yellow_single_川V11082_mask_0_iter_7_generated_川Q11082.jpg

# visualdl --logdir . --model /yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/inference/inference.pdmodel --port 8080

# 模型转换
# python3 tools/export_model.py -c /yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/config.yml -o Global.pretrained_model=/yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/iter_epoch_500  Global.save_inference_dir=/yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/inference/
# 注：转模型注意事项：
# 1、ppocr/modeling/backbones/rmai_rec_mobilenet_v1.py, 200 -> 206
# 2、ppocr/modeling/heads/rec_ctc_head.py, 176 -> 180, 156 -> 161(162)
# 3、tools/export_model.py, 75 -> 76, 192 -> 193

# 模型转换
# paddle2onnx --model_dir /yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/inference \
# --model_filename inference.pdmodel \
# --params_filename inference.pdiparams \
# --save_file /yuanhuan/model/image/lpr/paddle_ocr/v1_chile_mobilenet_v1_rm_cnn_tc_res_mobile_rmresize_gray_128_256_202312_w_diffste_w_aug/inference/onnx/model.onnx \
# --opset_version 10 \
# --enable_onnx_checker True